name: CI
on: [ push, pull_request ]
jobs:
  Build:

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        node-version: [ 20 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Install Browsers
      if: runner.os == 'Linux'
      run: npx playwright install chromium firefox --with-deps
    - name: Install Browsers
      if: runner.os != 'Linux'
      run: npx playwright install chromium --with-deps
    - name: Build
      if: runner.os == 'Linux'
      env:
        HEADLESS: 1
        TEST_BROWSERS: chromium,firefox
      run: xvfb-run npm run all
    - name: Build
      if: runner.os != 'Linux'
      env:
        HEADLESS: 1
        TEST_BROWSERS: chromium
      run: npm run all
